[2013-09-27 14:33:01.754000]
ERROR
	'[Failure instance: Traceback from remote host -- Traceback unavailable\nexceptions.KeyError: 50000041L\n]'
